apiVersion: v1
kind: Service
metadata:
  name: web-service-staging
  namespace: webapps-staging
spec:
  selector:
    app: webapp-staging
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
